name: Tests

on:
  push:
    branches: [ main ]
  pull_request: ~
  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        python-version: [ "3.7", "3.12" ]

    name: Python ${{ matrix.python-version }} on OS ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements-release.txt
            requirements-test.txt
            setup.py

      - name: Install program
        run: |
          pip install --requirement=requirements-test.txt
          pip install --editable=.[service]
          playwright install firefox

      - name: Run tests
        run: pytest
